### ISSUE TITLE
storybook infolistitem "array for subtitles" not rendering icon subtitle properly

### ISSUE THREAD

**Issue by huayunh** [pxblue/react-native-component-library#49]
#### Describe the bug
On storybook, under the `infolistitem` component, the "array for subtitles" story is not properly rendered. The `<Leaf>` icon is missing and not rendered. 

#### What is the expected behavior?
Should be rendered. 

#### What are the steps to reproduce?
1. `yarn start:storybook-android`
2. Go to 'array for subtitles' story under infolistitem component. 

#### Screenshots or links to minimum reproduction example
![image](https://user-images.githubusercontent.com/8997218/84826408-e8be0300-aff0-11ea-9fe2-407dae32eea9.png)

#### What is your environment?

Framework
React Native

Operating System
Android emulator pixel 3a API 28
		
#### Anything else to add?
No console warnings or IDE warnings are triggered as far as I can tell.

**Comment by joebochill** [comment]
Turns out this is a bigger issue than just the ILI subtitles. When you use an SVG directly through react-native-svg, it will show up transparent (any paths that don't explicitly have a fill prop in the svg show up transparent). The default used to be for these to appear black, but a recent change seems to have broken it (https://github.com/react-native-community/react-native-svg/issues/1354). We can get around this by setting the fill property on the icons manually.
