### ISSUE TITLE
InfoListItem should accept material icons

### ISSUE THREAD

**Issue by huayunh** [pxblue/react-native-component-library#73]
#### Describe the desired behavior
InfoListItem should allow me to do 
```tsx
<InfoListItem 
    title={'xxx'}
    icon={<MatIcon name="brightness6" />} 
/>
```

#### Describe the current behavior
It only takes an `IconClass` prop, which only accepts `React.Component<{ size: number, color: string }>` (and thus only PXBlue icons?)

#### Is this request related to a current issue?
The empty state has some similar concern #69

**Comment by joebochill** [comment]
The `iconWrapper` utility works equally well for PX Blue icons and MaterialIcons...plus any of the other icon libraries available in react-native-vector-icons: https://github.com/pxblue/react-native-component-library/blob/dev/docs/IconWrapper.md#usage-react-native-vector-icons

The reason we cannot currently pass in icon or other elements directly is because we lose the ability to control the size. In the web, these icons are sized by the fontSize property, so we can allow them to be passed in with 'inherit' and simply set a fontSize on a wrapper element. However, style inheritance is very very limited in RN (limited to nested Text elements only, and only certain properties). So passing in an element like `icon={<SomeComponent/>}` would mean the end user would be responsible for correctly sizing the component/icon according to the specs. This was the primary motivation behind creating the `iconWrapper` utility.

**Comment by joebochill** [comment]
Since Material Icons can be used with iconWrapper, we'll close this issue. Further discussion about the use of iconWrapper vs. directly passing in components can follow up in #69
